version: 2
updates:
  - package-ecosystem: github-actions
    directory: "./github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: .devcontainer/
    schedule:
      interval: weekly
      time: "04:00"
      day: sunday
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
      day: sunday
    open-pull-requests-limit: 5
